---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lldpd-sa
  namespace: lldpd
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lldpd:privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: lldpd-sa
  namespace: lldpd